# Generated by Django 4.2.14 on 2024-07-19 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='first_name',
            field=models.CharField(default='-', max_length=255, null=True, unique=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='last_name',
            field=models.CharField(default='-', max_length=255, null=True, unique=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.chatuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='user_id',
            field=models.IntegerField(verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
